# Generated by Django 6.0.3 on 2026-03-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursethread',
            name='thread_type',
            field=models.CharField(choices=[('course', 'Course Message'), ('pm', 'Private Message'), ('ai', 'AI Conversation'), ('system', 'System'), ('support', 'Support')], max_length=20),
        ),
    ]
