# Generated by Django 6.0.3 on 2026-03-25 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_lead_sessions', models.BooleanField(default=True)),
                ('can_answer_students', models.BooleanField(default=True)),
                ('can_grade', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('audience_type', models.CharField(choices=[('adults_only', 'Adults only'), ('children_only', 'Children only'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ai_external_processing_allowed', models.BooleanField(default=True)),
                ('client_side_ai_only', models.BooleanField(default=False)),
                ('strict_privacy_mode', models.BooleanField(default=False)),
                ('course_recording', models.BooleanField(default=False)),
                ('course_recording_stream', models.BooleanField(default=False)),
                ('course_recording_chat_history', models.BooleanField(default=False)),
                ('course_recording_chat_group_history', models.BooleanField(default=False)),
                ('course_chat_students_allowed', models.BooleanField(default=True)),
                ('course_chat_students_with_ai_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('enrollment_open', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('professor', 'Professor'), ('ai_professor', 'AI Professor'), ('student', 'Student'), ('moderator', 'Moderator'), ('demonstrator', 'Demonstrator')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended'), ('removed', 'Removed'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=32)),
                ('can_manage_content', models.BooleanField(default=False)),
                ('can_manage_enrollment', models.BooleanField(default=False)),
                ('can_reply_inbox', models.BooleanField(default=False)),
                ('can_moderate_comments', models.BooleanField(default=False)),
                ('can_grade', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academy.semester')),
            ],
            options={
                'unique_together': {('semester', 'user', 'role')},
            },
        ),
    ]
