# Generated by Django 6.0.3 on 2026-03-31 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('liveclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='grouping_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClassroomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='liveclasses.classsession')),
                ('thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_group', to='communication.thread')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='liveclasses.classroomgroup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='liveclasses.sessionparticipant')),
            ],
            options={
                'unique_together': {('group', 'participant')},
            },
        ),
    ]
