# Generated by Django 6.0.3 on 2026-03-31 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0002_classsession_grouping_active_classroomgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackboardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='blackboard/%Y/%m/')),
                ('file_type', models.CharField(choices=[('text', 'Plain Text'), ('markdown', 'Markdown'), ('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackboard_files', to='liveclasses.classsession')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BlackboardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fullscreen', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('scroll_y', models.IntegerField(default=0)),
                ('zoom', models.IntegerField(default=100)),
                ('rotation', models.IntegerField(default=0)),
                ('media_playing', models.BooleanField(default=False)),
                ('active_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liveclasses.blackboardfile')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blackboard_state', to='liveclasses.classsession')),
            ],
        ),
    ]
